### ISSUE TITLE
Delete a Teams channel

### ISSUE THREAD

**Issue by mprnci** [microsoftgraph/msgraph-sdk-python#147] opened 2023-03-30 15:37 UTC
Hello,

The issue https://github.com/microsoftgraph/msgraph-sdk-python/issues/80#issue-1565989855 has been closed but I still have the same error. When doing:

```
# DELETE A TEAMS CHANNEL

async def delete_channel():
    try:
        await client.teams_by_id('TEAM_ID').channels_by_id('CHANNEL_ID').delete()
    except Exception as e:
        print(e.error.message)
asyncio.run(delete_channel())
```

I get the errror:

`await client.teams_by_id(team_id).channels_by_id(channel_id).delete() AttributeError: 'ChannelItemRequestBuilder' object has no attribute 'delete'`

The packages are already the same version as mentioned here https://github.com/microsoftgraph/msgraph-sdk-python/blob/main/Pipfile

Is the issue supposed to be fixed or is it still awaiting?
Or maybe these are not the right packages version?

Thank you in advance!

**Comment by samwelkanda** [comment] 2023-04-20 11:00
Hey @mprnci 

Thank you for reporting this issue. The above was caused by metadata changes in the underlying API which caused some paths not to be generated. It has since been resolved in later versions of the SDK.

Please note that the call syntax has changed as from `v1.0.0a12` as will now be
 
`await client.teams.by_team_id('TEAM_ID').channels.by_channel_id('CHANNEL_ID').delete()`

Thanks.

**Comment by samwelkanda** [comment] 2023-04-20 11:01
Closing for now, feel free to re-open if you have further questions.

**Closed as completed by samwelkanda** 2023-04-20 11:01 UTC
Labels: bug
