### ISSUE TITLE
How to get notified for SharePoint permission changes on users/groups/documents?

### ISSUE THREAD

**Issue by mingchun-zhao** [microsoftgraph/msgraph-sdk-python#75] opened 2023-01-28 09:00 UTC
Hi, do you have any idea about how to detect SharePoint permission changes on users/groups/documents?

**Comment by andrueastman** [comment] 2024-04-15 09:31
Thank you for reporting this issue. This appears to be a question with the service APIs. Unfortunately, as the Microsoft Graph SDK team, we do not have ownership of the APIs that are causing you issues. We invite you to create a question about the service API to Microsoft Q&A and tagged with one of the [microsoft-graph-*] tags, that way it will get routed to the appropriate team for them to triage:  
 
https://aka.ms/msgraphsupport or directly https://aka.ms/askgraph 

For now, we will close the issue on our side but feel free to open it in the relevant repository if you think the issue is specific to SDK.

**Closed as completed by andrueastman** 2024-04-15 09:31 UTC
Labels: question
