### ISSUE TITLE
Missing enum value `WindowsDefault` in `AutomaticUpdateMode`

### ISSUE THREAD

**Issue by pokop** [microsoftgraph/msgraph-sdk-python#415] opened 2023-10-17 13:26 UTC
According to [this MSDN page](https://learn.microsoft.com/en-us/graph/api/intune-deviceconfig-windowsupdateforbusinessconfiguration-create?view=graph-rest-1.0&tabs=python), there is another possible value for `AutomaticUpdateMode` enum - `WindowsDefault`.

Adding `WindowsDefault = "windowsDefault",` by the end of `automatic_update_mode.py` solved the exceptions I had.

**Comment by samwelkanda** [comment] 2023-11-01 14:40
Hi @pokop 

Thanks for creating this issue. 

Indeed I have confirmed the `WindowsDefault` enum option is available in the docs. However it's missing in the Graph API [metadata](https://[graph.microsoft.com/v1.0/$metadata](https://graph.microsoft.com/v1.0/$metadata)) document that we use to generate the SDK.

![image](https://github.com/microsoftgraph/msgraph-sdk-python/assets/40166690/5be2c514-f4bc-4043-b6c2-9b84db62f4b3)

Since this is not an issue with the SDK itself, I recommend you open a ticket on the Microsoft Graph [Q&A portal](https://learn.microsoft.com/en-us/answers/tags/161/ms-graph) and the specific team will be able to confirm if the option is available or deprecated.

Thanks.

**Comment by samwelkanda** [comment] 2023-11-01 14:42
Closing for now. Please do share a link on this issue to the ticket on the Q&A site for reference.

**Closed as completed by samwelkanda** 2023-11-01 14:42 UTC
Labels: bug
