### ISSUE TITLE
Application - Property difference between AD Graph and MS Graph 

### ISSUE THREAD

**Issue by xuzhang3** [microsoftgraph/msgraph-sdk-python#409] opened 2023-10-11 06:59 UTC
There are five property differences between AD Graph and MS Graph, four of which  can found at : https://learn.microsoft.com/en-us/graph/migrate-azure-ad-graph-property-differences#device-property-differences

```python
available_to_other_tenants
homepage
reply_urls
oauth2_allow_implicit_flow
```

There is no replacement property for `allow_guests_sign_in` in MS Graph, is this attribute deprecated?

**Comment by andrueastman** [comment] 2024-04-15 09:22
Thank you for reporting this issue. This appears to be an issue or limitation with the service APIs. Unfortunately, as the Microsoft Graph SDK team, we do not have ownership of the APIs that are causing you issues. We invite you to create a question about the service API to Microsoft Q&A and tagged with one of the [microsoft-graph-*] tags, that way it will get routed to the appropriate team for them to triage:  
 
https://aka.ms/msgraphsupport or directly https://aka.ms/askgraph 

For now, we will close the issue on our side but feel free to open it in the relevant repository if you think the issue is specific to SDK.

**Closed as completed by andrueastman** 2024-04-15 09:22 UTC
